### ISSUE TITLE
Bug: install script does not work with Python >3.7

### ISSUE THREAD

**Issue by w-klijn** [Meta-optimization/L2L#41]
attributeError: module 'platform' has no attribute 'linux_distribution'
Specifically this is caused because the matplot lib needed for L2L is an old one. (<3.1)

https://stackoverflow.com/questions/63636697/error-module-platform-has-no-attribute-linux-distribution

Why is L2L dependend on such an old matplotlib?
Why is L2L plotting?

**Comment by alperyeg** [comment]
The CI is only running on Python 3.7 - 3.9. But matplab  should be removed in general.
